name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Changed Files Exporter
      uses: futuratrepadeira/changed-files@v3.0.0
      id: changed-files
      with:
        repo-token: ${{ github.token }}
    - name: set FILES
      run: |
        echo "::set-env name=FILES::${{ steps.changed-files.outputs.files_created }} ${{ steps.changed-files.outputs.files_updated }} ${{ steps.changed-files.outputs.files_deleted }}"
    - uses: deepyaman/action@v1.0.2 
      with:
        args: --files ${{ env.FILES }}
        token: ${{ secrets.GITHUB_TOKEN }}